"""add file_unique_id with owner scope

Revision ID: c61971f0c82a
Revises: 0caa6a1c1bc2
Create Date: 2025-07-01 14:48:35.631046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61971f0c82a'
down_revision: Union[str, Sequence[str], None] = '0caa6a1c1bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
