"""add file_unique_id to audio_files

Revision ID: e3f2e75b50bf
Revises: c61971f0c82a
Create Date: 2025-07-01 15:03:46.710202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f2e75b50bf'
down_revision: Union[str, Sequence[str], None] = 'c61971f0c82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('file_unique_id', sa.String(), nullable=False))
    op.create_unique_constraint('uix_owner_file', 'audio_files', ['owner_id', 'file_unique_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_owner_file', 'audio_files', type_='unique')
    op.drop_column('audio_files', 'file_unique_id')
    # ### end Alembic commands ###
